name: Backend CI
'on':
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SECRET_KEY : ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python and Pipenv
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv lock  # Generate the lock file if you haven't already
          pipenv sync --dev  # Install all dependencies (including dev packages)
      - name: Run Django migrations
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SECRET_KEY : ${{ secrets.SECRET_KEY }}
        run: pipenv run python manage.py migrate
      - name: Run tests
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SECRET_KEY : ${{ secrets.SECRET_KEY }}
        run: pipenv run python manage.py test
