name: Backend CI/CD

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'

jobs:
  test:
    name: Test Django Application
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: your_test_db_user
          POSTGRES_PASSWORD: your_test_db_password
          POSTGRES_DB: your_test_db_name
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and pipenv
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PostgreSQL client
        run: apt-get update && apt-get install -y libpq-dev

      - name: Install pipenv and dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Set up environment variables
        env:
          DATABASE_URL: postgres://your_test_db_user:your_test_db_password@localhost:5432/your_test_db_name

      - name: Run tests
        run: |
          pipenv run python manage.py test


