name: CI/CD for Django

on:
  push:
    branches:
      - main
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: 'QA'

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: pipenv install --dev

      - name: Run Migrations
        run: pipenv run python manage.py migrate

      - name: Run Tests
        run: pipenv run python manage.py test
        
      # Install Git Flow CLI
      - name: Install Git Flow CLI
        run: |
          apt-get update -qy
          apt-get install -y git-flow

      # Finish Feature Branch (if applicable)
      - name: Finish Feature Branch
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          git config gitflow.prefix.feature "feature/"
          git checkout main
          git pull origin main
          git flow feature finish ${{ github.head_ref }}
          git push origin main