name: Django CI

on:
  push:
    branches: [ "feature/auth" ]
  pull_request:
    branches: [ "feature/auth" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: |
          python -m pip install --upgrade pip
          pip install pipenv

    - name: Install Dependencies
      run: |
        pipenv install --dev

    - name: Run Tests
      run: |
        python manage.py test
    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages