name: Django CI

on:
  push:
    branches: [ "feature/auth" ]
  pull_request:
    branches: [ "feature/auth" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Activate virtual environment
      run: pipenv shell

    - name: Install pipenv
      run: |
          python -m pip install --upgrade pip
          pip install pipenv

    - name: Install Dependencies
      run: |
        pipenv install --dev
    - name: Cache pip dependencies

      uses: actions/cache@v2
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}

    - name: Run Tests
      run: |
        python manage.py test

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      with:
          publish_dir: ./docs
          publish_branch: gh-pages