name: Pre-Merge Check

on:
  pull_request:
    types:
      - synchronize

jobs:
  check_ci_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check CI status
        run: |
          # Replace OWNER and REPO with your GitHub repository information
          STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/OWNER/REPO/actions/workflows/ci-cd.yml/runs?event=pull_request" | jq -r '.workflow_runs[0].status')
          if [[ "$STATUS" != "completed" || "$(echo "$STATUS" | tr '[:upper:]' '[:lower:]')" != "success" ]]; then
            echo "CI/CD workflow status: $STATUS"
            echo "Merging blocked: CI/CD workflow must pass before merging."
            exit 1
          fi
